AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 25

Layout/LineLength:
  Max: 120
